from pydantic import BaseModel

class AuthData(BaseModel): email: str; password: str = ""; name: str = ""; otp_code: str = ""
class RoleData(BaseModel): email: str; role: str; is_head: int = 0
class UserInviteData(BaseModel): email: str; name: str; role: str; password: str; is_head: int = 0
class ClientData(BaseModel): name: str; inn: str = ""; kpp: str = ""; ogrn: str = ""; legal_address: str = ""; contact: str = ""
class BusinessObjectData(BaseModel): client_id: int = 0; name: str = ""; code: str = ""; address: str = ""; city: str = ""; region: str = ""; responsible_name: str = ""; responsible_email: str = ""; comment: str = ""
class ContractMasterData(BaseModel): project_id: int = 0; client_id: int = 0; object_id: int = 0; contract_number: str = ""; title: str = ""; status: str = "draft"; amount: float = 0; currency: str = "RUB"; start_date: str = ""; end_date: str = ""; manager_name: str = ""; manager_email: str = ""; comment: str = ""; custom_fields: list = []; contract_type: str = "standard"; category: str = ""; folder: str = "Все договоры"; vat_mode: str = "with_vat"; risk_level: str = "normal"

# --- НОВЫЕ СХЕМЫ ДЛЯ НСИ И СКЛАДА ---
class NomenclatureData(BaseModel): name: str; article: str = ""; unit: str = "шт"; price: float = 0; stock: float = 0; currency: str = "RUB"; group_name: str = ""; default_warehouse: str = ""
class StockMovement(BaseModel): qty: float; type: str # 'add' или 'remove'
class ContactData(BaseModel): client_id: int = 0; name: str; phone: str = ""; email: str = ""; position: str = ""

# Обновленные схемы проекта
class ProjectData(BaseModel): name: str; contract: str = "ТБД"; client: str = ""; manager: str = ""; budget: float = 0; costs: float = 0; team: list = []; checklist: list = []; allowed_roles: list = []; nomenclature: list = []; archive_details: dict = {}
class ProjectUpdate(BaseModel): name: str; contract: str; client: str; manager: str; progress: float; status: str; checkedState: dict; comments: dict; deadlines: dict; budget: float = 0; costs: float = 0; chat: list = []; files: list = []; logs: list = []; team: list = []; checklist: list = []; escalations: dict = {}; archive_details: dict = {}; taskFiles: dict = {}; subtasks: dict = {}; time_logs: list = []; allowed_roles: list = []; nomenclature: list = []
class TenderParseData(BaseModel): source: str = ""; text: str = ""
class ContractScanData(BaseModel): text: str
class FinancePaymentData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; legal_entity_id: int = 0; business_unit_id: int = 0; treasury_article_id: int = 0; vat_rate_id: int = 0; source_document_type: str = ""; source_document_id: int = 0; title: str = ""; kind: str = "incoming"; category: str = "payment"; amount: float = 0; currency: str = "RUB"; due_date: str = ""; paid_date: str = ""; status: str = "planned"; comment: str = ""
class FinanceMasterRecordData(BaseModel): name: str = ""; short_name: str = ""; inn: str = ""; kpp: str = ""; ogrn: str = ""; vat_mode: str = "osno"; default_currency: str = "RUB"; legal_entity_id: int = 0; code: str = ""; manager_name: str = ""; flow_kind: str = "incoming"; category: str = ""; rate: float = 0; is_default: int = 0; is_active: int = 1
class TreasuryLimitData(BaseModel): period_key: str = ""; legal_entity_id: int = 0; business_unit_id: int = 0; treasury_article_id: int = 0; amount_limit: float = 0; status: str = "active"
class FinancePeriodCloseData(BaseModel): period_key: str = ""; comment: str = ""
class ReconciliationActData(BaseModel): client_id: int = 0; contract_id: int = 0; period_key: str = ""; act_number: str = ""; amount_receivable: float = 0; amount_payable: float = 0; details: dict = {}; status: str = "draft"
class EDOSignatureData(BaseModel): entity_type: str = ""; entity_id: int = 0; signer_name: str = ""; signer_role: str = ""; certificate_thumbprint: str = ""; signature_provider: str = "1С-ЭДО"; signature_status: str = "signed"; signed_at: str = ""; comment: str = ""
class FinanceInboundSyncItem(BaseModel): entity_type: str = "finance_payment"; entity_id: int = 0; external_id: str = ""; status: str = ""; amount: float = 0; currency: str = "RUB"; due_date: str = ""; paid_date: str = ""; comment: str = ""; source_document_type: str = ""; source_document_id: int = 0; exchange_state: str = "synced"; allow_amount_override: int = 0; payload: dict = {}; idempotency_key: str = ""; correlation_id: str = ""
class FinanceInboundSyncData(BaseModel): items: list[dict] = []; source_system: str = "1C"; actor_note: str = ""; idempotency_key: str = ""; correlation_id: str = ""
class IntegrationSyncBatchData(BaseModel): items: list[dict] = []; source_system: str = "1C"; actor_note: str = ""; idempotency_key: str = ""; correlation_id: str = ""
class WorkbenchWatchData(BaseModel): entity_type: str = ""; entity_id: str = ""; title: str = ""; meta: str = ""; view_name: str = ""; condition_key: str = "any_change"; digest_mode: str = "instant"; event_types: list[str] = []
class PurchaseOrderData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; legal_entity_id: int = 0; business_unit_id: int = 0; item_article: str = ""; item_name: str = ""; supplier: str = ""; supplier_id: int = 0; qty: float = 0; unit: str = "шт"; unit_price: float = 0; planned_unit_price: float = 0; status: str = "planned"; expected_date: str = ""; planned_delivery_date: str = ""; received_date: str = ""; delivered_qty: float = 0; request_status: str = "draft"; approval_status: str = "not_required"; schedule_status: str = "planned"; lead_time_days: int = 0; comment: str = ""
class SalesDocumentData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; legal_entity_id: int = 0; business_unit_id: int = 0; doc_type: str = "invoice"; doc_number: str = ""; doc_date: str = ""; amount: float = 0; currency: str = "RUB"; status: str = "draft"; payment_status: str = "planned"; linked_payment_id: int = 0; customer_order_no: str = ""; shipment_status: str = "not_shipped"; payment_due_date: str = ""; planned_ship_date: str = ""; shipped_at: str = ""; reserve_status: str = "none"; reserve_qty: float = 0; price_list_id: int = 0; discount_percent: float = 0; discount_amount: float = 0; comment: str = ""; recipient_email: str = ""; sent_status: str = "draft"; sent_at: str = ""; delivered_at: str = ""; confirmed_at: str = ""
class ProductionOrderData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; legal_entity_id: int = 0; business_unit_id: int = 0; order_name: str = ""; stage: str = "queue"; priority: str = "normal"; planned_start: str = ""; planned_finish: str = ""; actual_finish: str = ""; progress: int = 0; responsible: str = ""; route_name: str = ""; planned_qty: float = 0; produced_qty: float = 0; scrap_qty: float = 0; planned_cost: float = 0; actual_cost: float = 0; labor_hours_plan: float = 0; labor_hours_fact: float = 0; comment: str = ""
class ProductionOperationData(BaseModel): order_id: int = 0; sequence_no: int = 1; operation_name: str = ""; work_center: str = ""; status: str = "planned"; planned_hours: float = 0; actual_hours: float = 0; planned_qty: float = 0; completed_qty: float = 0; scrap_qty: float = 0; labor_rate: float = 0; material_cost: float = 0; overhead_cost: float = 0; started_at: str = ""; finished_at: str = ""; note: str = ""
class ProductionBOMItemData(BaseModel): order_id: int = 0; article: str = ""; item_name: str = ""; unit: str = "шт"; qty_per_unit: float = 0; planned_qty: float = 0; actual_qty: float = 0; unit_cost: float = 0; warehouse: str = ""; bin_code: str = ""; note: str = ""
class ProductionRouteTemplateData(BaseModel): order_id: int = 0; sequence_no: int = 1; operation_name: str = ""; work_center: str = ""; planned_hours: float = 0; planned_qty: float = 0; labor_rate: float = 0; note: str = ""
class StockReservationData(BaseModel): project_id: int = 0; legal_entity_id: int = 0; business_unit_id: int = 0; nomenclature_article: str = ""; nomenclature_name: str = ""; qty: float = 0; status: str = "reserved"; comment: str = ""; warehouse: str = ""; bin_code: str = ""; batch_code: str = ""; serial_no: str = ""
class SalesQuoteData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; title: str = ""; quote_number: str = ""; stage: str = "draft"; amount: float = 0; currency: str = "RUB"; valid_until: str = ""; responsible: str = ""; probability: int = 0; comment: str = ""
class SalesCustomerOrderData(BaseModel): quote_id: int = 0; sales_document_id: int = 0; project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; legal_entity_id: int = 0; business_unit_id: int = 0; order_number: str = ""; article: str = ""; item_name: str = ""; qty: float = 0; unit: str = "шт"; unit_price: float = 0; amount: float = 0; currency: str = "RUB"; status: str = "draft"; requested_ship_date: str = ""; payment_terms: str = ""; comment: str = ""
class SalesCustomerOrderReserveData(BaseModel): warehouse: str = ""; bin_code: str = ""; batch_code: str = ""; serial_no: str = ""; qty: float = 0; comment: str = ""
class SalesShipmentData(BaseModel): customer_order_id: int = 0; sales_document_id: int = 0; reservation_id: int = 0; shipment_number: str = ""; article: str = ""; item_name: str = ""; qty: float = 0; warehouse: str = ""; bin_code: str = ""; batch_code: str = ""; serial_no: str = ""; planned_ship_date: str = ""; shipped_at: str = ""; status: str = "planned"; carrier: str = ""; tracking_no: str = ""; comment: str = ""
class SalesPaymentScheduleData(BaseModel): customer_order_id: int = 0; sales_document_id: int = 0; payment_id: int = 0; schedule_number: str = ""; due_date: str = ""; amount: float = 0; currency: str = "RUB"; status: str = "planned"; paid_amount: float = 0; paid_date: str = ""; comment: str = ""
class SalesDealMarginData(BaseModel): customer_order_id: int = 0; sales_document_id: int = 0; direct_cost_amount: float = 0; discount_amount: float = 0; comment: str = ""
class CustomerReturnData(BaseModel): project_id: int = 0; client_id: int = 0; sales_document_id: int = 0; return_number: str = ""; article: str = ""; item_name: str = ""; qty: float = 0; amount: float = 0; currency: str = "RUB"; warehouse: str = ""; bin_code: str = ""; status: str = "draft"; reason: str = ""; comment: str = ""
class SalesPlanData(BaseModel): period_key: str = ""; manager_name: str = ""; client_id: int = 0; project_id: int = 0; target_amount: float = 0; target_docs: int = 0; actual_amount: float = 0; status: str = "draft"; comment: str = ""
class PriceListData(BaseModel): name: str = ""; currency: str = "RUB"; valid_from: str = ""; valid_to: str = ""; item_article: str = ""; item_name: str = ""; unit: str = "шт"; base_price: float = 0; min_price: float = 0; status: str = "active"; comment: str = ""
class ClientSalesTermData(BaseModel): client_id: int = 0; price_list_id: int = 0; discount_percent: float = 0; discount_amount: float = 0; payment_delay_days: int = 0; credit_limit: float = 0; shipment_priority: str = "normal"; status: str = "active"; comment: str = ""
class SupplierRegistryData(BaseModel): supplier_name: str = ""; legal_entity_name: str = ""; inn: str = ""; category: str = ""; rating: float = 0; lead_time_days: int = 0; reliability_percent: float = 100; payment_terms: str = ""; comment: str = ""; is_active: int = 1
class PurchasePlanData(BaseModel): period_key: str = ""; supplier_id: int = 0; project_id: int = 0; item_article: str = ""; item_name: str = ""; qty_plan: float = 0; unit: str = "шт"; target_unit_price: float = 0; target_amount: float = 0; status: str = "draft"; comment: str = ""
class SupplierDeliveryScheduleData(BaseModel): purchase_id: int = 0; supplier_id: int = 0; scheduled_date: str = ""; planned_qty: float = 0; delivered_qty: float = 0; status: str = "planned"; transport_no: str = ""; comment: str = ""
class SupplierReturnData(BaseModel): purchase_id: int = 0; supplier_id: int = 0; article: str = ""; item_name: str = ""; qty: float = 0; amount: float = 0; currency: str = "RUB"; warehouse: str = ""; bin_code: str = ""; status: str = "draft"; reason: str = ""; comment: str = ""
class SupplierDiscrepancyActData(BaseModel): purchase_id: int = 0; supplier_id: int = 0; act_number: str = ""; article: str = ""; item_name: str = ""; planned_qty: float = 0; actual_qty: float = 0; planned_unit_price: float = 0; actual_unit_price: float = 0; status: str = "open"; reason: str = ""; comment: str = ""
class ProcurementRequestData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; legal_entity_id: int = 0; business_unit_id: int = 0; request_number: str = ""; title: str = ""; item_article: str = ""; item_name: str = ""; qty: float = 0; unit: str = "шт"; target_unit_price: float = 0; required_date: str = ""; priority: str = "normal"; requested_by: str = ""; status: str = "draft"; comment: str = ""
class ProcurementTenderData(BaseModel): request_id: int = 0; tender_number: str = ""; title: str = ""; due_date: str = ""; status: str = "draft"; criteria: dict = {}; comment: str = ""
class ProcurementTenderBidData(BaseModel): tender_id: int = 0; supplier_id: int = 0; supplier_name: str = ""; price: float = 0; currency: str = "RUB"; lead_time_days: int = 0; payment_terms: str = ""; warranty_terms: str = ""; score: float = 0; status: str = "submitted"; comment: str = ""
class ProcurementAwardData(BaseModel): bid_id: int = 0; decision_comment: str = ""; create_purchase: int = 0
class PurchaseReceiptData(BaseModel): purchase_id: int = 0; request_id: int = 0; supplier_id: int = 0; receipt_number: str = ""; receipt_date: str = ""; article: str = ""; item_name: str = ""; accepted_qty: float = 0; rejected_qty: float = 0; warehouse: str = ""; bin_code: str = ""; lot_expiration_date: str = ""; unit_cost: float = 0; quality_status: str = "accepted"; status: str = "posted"; comment: str = ""
class PurchaseDocumentData(BaseModel): purchase_id: int = 0; request_id: int = 0; supplier_id: int = 0; doc_type: str = "invoice"; doc_number: str = ""; doc_date: str = ""; amount: float = 0; vat_amount: float = 0; currency: str = "RUB"; status: str = "draft"; payment_due_date: str = ""; linked_payment_id: int = 0; file_ref: str = ""; comment: str = ""
class ExpenseApprovalData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; title: str = ""; request_type: str = "payment"; amount: float = 0; currency: str = "RUB"; approver_role: str = "Директор"; approver_name: str = ""; due_date: str = ""; linked_payment_id: int = 0; status: str = "draft"; comment: str = ""
class InternalRequestData(BaseModel): project_id: int = 0; contract_id: int = 0; object_id: int = 0; title: str = ""; request_type: str = "purchase"; target_role: str = ""; assignee_name: str = ""; priority: str = "normal"; status: str = "new"; deadline: str = ""; comment: str = ""
class ResourceAllocationData(BaseModel): project_id: int = 0; contract_id: int = 0; object_id: int = 0; department: str = ""; resource_name: str = ""; role_name: str = ""; load_percent: int = 0; date_from: str = ""; date_to: str = ""; status: str = "planned"; comment: str = ""; crew_name: str = ""; crew_type: str = ""; location: str = ""
class ServiceCaseData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; case_number: str = ""; title: str = ""; case_type: str = "warranty"; status: str = "open"; priority: str = "normal"; defect: str = ""; warranty_until: str = ""; sla_deadline: str = ""; responsible: str = ""; resolution: str = ""
class BudgetLineData(BaseModel): project_id: int = 0; line_type: str = "cost"; category: str = ""; plan_amount: float = 0; fact_amount: float = 0; comment: str = ""
class StockMovementDetailedData(BaseModel): qty: float = 0; type: str = "add"; from_warehouse: str = ""; from_bin: str = ""; to_warehouse: str = ""; to_bin: str = ""; batch_code: str = ""; serial_no: str = ""; comment: str = ""
class StockReservationFulfillData(BaseModel): qty: float = 0; warehouse: str = ""; bin_code: str = ""; batch_code: str = ""; serial_no: str = ""; comment: str = ""
class NSIMasterRecordData(BaseModel): name: str = ""; code: str = ""; is_active: int = 1; comment: str = ""; short_name: str = ""; email: str = ""; phone: str = ""; personnel_number: str = ""; department_name: str = ""; characteristic_type: str = ""; warehouse_id: int = 0; zone_name: str = ""; article_kind: str = "expense"; module_name: str = ""; flow_kind: str = ""; legal_entity_id: int = 0; business_unit_id: int = 0; position_id: int = 0; manager_name: str = ""; bank_name: str = ""; account_number: str = ""; bik: str = ""; currency: str = "RUB"
class MDMGovernanceActionData(BaseModel): comment: str = ""; target_state: str = "active"
class NSIHierarchyData(BaseModel): hierarchy_type: str = "mdm"; entity_type: str = ""; entity_id: int = 0; parent_entity_id: int = 0; node_code: str = ""; node_name: str = ""; sort_order: int = 0; is_active: int = 1; valid_from: str = ""; valid_to: str = ""; details: dict = {}; comment: str = ""
class NSIExternalClassifierData(BaseModel): classifier_type: str = ""; source_system: str = "manual"; external_code: str = ""; external_parent_code: str = ""; name: str = ""; short_name: str = ""; entity_type: str = ""; entity_id: int = 0; effective_from: str = ""; effective_to: str = ""; version_tag: str = ""; status: str = "active"; data: dict = {}
class NSIExternalClassifierImportData(BaseModel): classifier_type: str = ""; source_system: str = "manual"; version_tag: str = ""; items: list[dict] = []; source_url: str = ""; token: str = ""; headers: dict = {}; limit: int = 2000
class NSIDuplicateRuleData(BaseModel): entity_type: str = ""; rule_name: str = ""; fields: list[str] = []; match_mode: str = "all"; severity: str = "error"; is_active: int = 1; comment: str = ""
class NSIBulkChangeRequestData(BaseModel): entity_type: str = ""; operation: str = "update_fields"; filter: dict = {}; changes: dict = {}; comment: str = ""
class InventoryDocumentData(BaseModel): doc_type: str = "inventory"; doc_number: str = ""; article: str = ""; warehouse: str = ""; bin_code: str = ""; batch_code: str = ""; serial_no: str = ""; lot_expiration_date: str = ""; target_warehouse: str = ""; target_bin: str = ""; qty: float = 0; counted_qty: float = 0; unit: str = "шт"; package_code: str = ""; package_qty: float = 0; unit_cost: float = 0; reason: str = ""; comment: str = ""
class InventoryActData(BaseModel): warehouse: str = ""; bin_code: str = ""; article: str = ""; item_name: str = ""; expected_qty: float = 0; counted_qty: float = 0; batch_code: str = ""; serial_no: str = ""; status: str = "draft"; comment: str = ""
class InventoryRegradingData(BaseModel): warehouse: str = ""; bin_code: str = ""; from_article: str = ""; from_name: str = ""; to_article: str = ""; to_name: str = ""; qty: float = 0; status: str = "draft"; reason: str = ""; comment: str = ""
class WarehouseQualityReportData(BaseModel): warehouse: str = ""; bin_code: str = ""; article: str = ""; item_name: str = ""; qty: float = 0; quality_status: str = "hold"; defect_kind: str = ""; decision: str = "inspect"; status: str = "open"; comment: str = ""
class WarehousePolicyData(BaseModel): cost_method: str = "fifo"; allow_negative_stock: int = 0; auto_pick_strategy: str = "best_fit"; comment: str = ""
class WarehouseBulkActionData(BaseModel): entity_type: str = "inventory_document"; action: str = "print"; ids: list[int] = []; comment: str = ""
class WMSCellProfileData(BaseModel): warehouse: str = ""; bin_code: str = ""; zone_name: str = ""; cell_type: str = "storage"; capacity_qty: float = 0; capacity_weight: float = 0; abc_class: str = ""; status: str = "active"; comment: str = ""
class WMSPutawayTaskData(BaseModel): receipt_id: int = 0; article: str = ""; item_name: str = ""; qty: float = 0; source_warehouse: str = ""; source_bin: str = ""; target_warehouse: str = ""; target_bin: str = ""; batch_code: str = ""; serial_no: str = ""; lot_expiration_date: str = ""; priority: str = "normal"; status: str = "open"; assigned_to: str = ""; comment: str = ""
class WMSPickWaveData(BaseModel): wave_number: str = ""; project_id: int = 0; source_type: str = "reservation"; priority: str = "normal"; planned_ship_date: str = ""; assigned_to: str = ""; reservation_ids: list[int] = []; comment: str = ""
class WMSPickTaskData(BaseModel): wave_id: int = 0; reservation_id: int = 0; article: str = ""; item_name: str = ""; qty: float = 0; picked_qty: float = 0; warehouse: str = ""; bin_code: str = ""; batch_code: str = ""; serial_no: str = ""; lot_expiration_date: str = ""; status: str = "open"; assigned_to: str = ""; comment: str = ""
class UnitConversionData(BaseModel): article: str = ""; from_unit: str = ""; to_unit: str = ""; factor: float = 1; is_base: int = 0; comment: str = ""
class ItemPackageData(BaseModel): article: str = ""; package_code: str = ""; package_name: str = ""; unit: str = "шт"; qty_per_package: float = 1; weight_kg: float = 0; volume_m3: float = 0; barcode: str = ""; is_default: int = 0; comment: str = ""
class WMSCycleCountData(BaseModel): count_number: str = ""; warehouse: str = ""; zone_name: str = ""; bin_code: str = ""; planned_date: str = ""; assigned_to: str = ""; comment: str = ""
class WMSCycleCountLineData(BaseModel): count_id: int = 0; article: str = ""; item_name: str = ""; warehouse: str = ""; bin_code: str = ""; batch_code: str = ""; serial_no: str = ""; expected_qty: float = 0; counted_qty: float = 0; status: str = "draft"; comment: str = ""
class SpecificationVersionData(BaseModel): project_id: int = 0; order_id: int = 0; label: str = ""; comment: str = ""; version_status: str = "draft"; items: list = []
class ProductionTechCardData(BaseModel): order_id: int = 0; title: str = ""; work_center: str = ""; setup_minutes: float = 0; run_minutes: float = 0; instruction: str = ""; quality_points: str = ""; status: str = "draft"; comment: str = ""
class ProductionShiftData(BaseModel): legal_entity_id: int = 0; business_unit_id: int = 0; shift_date: str = ""; shift_name: str = ""; work_center: str = ""; capacity_hours: float = 0; team_name: str = ""; supervisor_name: str = ""; status: str = "planned"; comment: str = ""
class ProductionJobData(BaseModel): order_id: int = 0; shift_id: int = 0; operation_id: int = 0; title: str = ""; work_center: str = ""; executor_name: str = ""; planned_qty: float = 0; completed_qty: float = 0; status: str = "queued"; started_at: str = ""; finished_at: str = ""; comment: str = ""
class ProductionMaterialNormData(BaseModel): order_id: int = 0; article: str = ""; item_name: str = ""; unit: str = "шт"; norm_qty: float = 0; scrap_rate: float = 0; substitute_article: str = ""; comment: str = ""
class ProductionLaborNormData(BaseModel): order_id: int = 0; operation_name: str = ""; work_center: str = ""; norm_hours: float = 0; rate_per_hour: float = 0; team_size: int = 1; comment: str = ""
class ProductionSemifinishedData(BaseModel): order_id: int = 0; article: str = ""; item_name: str = ""; qty: float = 0; stage_name: str = ""; warehouse: str = ""; status: str = "in_stock"; unit_cost: float = 0; comment: str = ""
class ProductionReworkData(BaseModel): order_id: int = 0; related_operation_id: int = 0; defect_name: str = ""; qty: float = 0; reason: str = ""; rework_route: str = ""; status: str = "open"; extra_cost: float = 0; comment: str = ""
class TerminalSessionData(BaseModel): terminal_code: str = ""; terminal_type: str = "warehouse"; device_uid: str = ""; operator_name: str = ""; current_zone: str = ""; status: str = "active"
class TerminalScanData(BaseModel): session_id: int = 0; terminal_code: str = ""; terminal_type: str = "warehouse"; scan_kind: str = "barcode"; scan_value: str = ""; entity_type: str = ""; entity_id: int = 0; action_name: str = "lookup"; payload: dict = {}
class ProductionExecutionEventData(BaseModel): order_id: int = 0; operation_id: int = 0; job_id: int = 0; event_type: str = "start"; qty: float = 0; scrap_qty: float = 0; work_center: str = ""; executor_name: str = ""; payload: dict = {}
class ProductionPlanningScenarioData(BaseModel): scenario_name: str = ""; planning_horizon_days: int = 30; demand_mode: str = "confirmed_orders"; status: str = "active"; demand_multiplier: float = 1; capacity_multiplier: float = 1; lead_time_days: int = 0; freeze_days: int = 0; comment: str = ""
class ProductionMRPRunData(BaseModel): scenario_id: int = 0; run_name: str = ""; persist: int = 1
class ProductionBOMMasterData(BaseModel): item_article: str = ""; item_name: str = ""; bom_code: str = ""; bom_name: str = ""; status: str = "draft"; default_version_id: int = 0; unit: str = "шт"; output_qty: float = 1; legal_entity_id: int = 0; business_unit_id: int = 0; comment: str = ""
class ProductionBOMVersionData(BaseModel): bom_id: int = 0; version_no: str = "1"; status: str = "draft"; valid_from: str = ""; valid_to: str = ""; output_qty: float = 1; components: list[dict] = []; operations: list[dict] = []; overhead_rules: dict = {}; comment: str = ""
class ProductionWorkCenterData(BaseModel): center_code: str = ""; center_name: str = ""; center_type: str = "production"; legal_entity_id: int = 0; business_unit_id: int = 0; capacity_per_hour: float = 0; hourly_rate: float = 0; overhead_rate: float = 0; calendar_code: str = ""; status: str = "active"; comment: str = ""
class ProductionWorkCenterCalendarData(BaseModel): work_center_id: int = 0; calendar_date: str = ""; shift_code: str = "day"; available_hours: float = 0; capacity_qty: float = 0; status: str = "available"; comment: str = ""
class FinancePaymentRequestData(BaseModel): project_id: int = 0; client_id: int = 0; legal_entity_id: int = 0; business_unit_id: int = 0; title: str = ""; amount: float = 0; currency: str = "RUB"; due_date: str = ""; approver_name: str = ""; approval_status: str = "draft"; request_status: str = "draft"; linked_payment_id: int = 0; comment: str = ""
class TreasuryProjectLimitData(BaseModel): period_key: str = ""; project_id: int = 0; business_unit_id: int = 0; amount_limit: float = 0; status: str = "active"; comment: str = ""
class FinanceBudgetData(BaseModel): budget_type: str = "pnl"; period_key: str = ""; project_id: int = 0; business_unit_id: int = 0; article_name: str = ""; plan_amount: float = 0; fact_amount: float = 0; status: str = "draft"; comment: str = ""
class FinanceObligationData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; supplier_name: str = ""; obligation_type: str = "supplier"; title: str = ""; amount: float = 0; currency: str = "RUB"; due_date: str = ""; linked_payment_id: int = 0; status: str = "open"; comment: str = ""
class CashGapScenarioData(BaseModel): period_key: str = ""; scenario_name: str = ""; opening_balance: float = 0; expected_inflow: float = 0; expected_outflow: float = 0; gap_amount: float = 0; action_plan: str = ""; status: str = "draft"; comment: str = ""
class AccountingManualOperationData(BaseModel): entry_date: str = ""; legal_entity_id: int = 0; business_unit_id: int = 0; project_id: int = 0; client_id: int = 0; account_debit: str = ""; account_credit: str = ""; amount: float = 0; vat_amount: float = 0; description: str = ""; status: str = "draft"; comment: str = ""
class DebtAdjustmentData(BaseModel): client_id: int = 0; contract_id: int = 0; adjustment_date: str = ""; amount: float = 0; adjustment_kind: str = "writeoff"; reason: str = ""; account_debit: str = ""; account_credit: str = ""; status: str = "draft"; comment: str = ""
class CashOperationData(BaseModel): legal_entity_id: int = 0; business_unit_id: int = 0; project_id: int = 0; operation_date: str = ""; direction: str = "incoming"; category: str = "cash"; amount: float = 0; currency: str = "RUB"; cashbox_name: str = ""; counterparty_name: str = ""; linked_payment_id: int = 0; account_debit: str = ""; account_credit: str = ""; status: str = "draft"; comment: str = ""
class TreasuryApprovalRouteData(BaseModel): route_name: str = ""; legal_entity_id: int = 0; business_unit_id: int = 0; min_amount: float = 0; max_amount: float = 0; currency: str = "RUB"; stages: list[dict] = []; is_default: int = 0; is_active: int = 1; comment: str = ""
class BankPaymentOrderData(BaseModel): payment_id: int = 0; bank_account_id: int = 0; legal_entity_id: int = 0; business_unit_id: int = 0; order_date: str = ""; amount: float = 0; currency: str = "RUB"; counterparty: str = ""; purpose: str = ""; status: str = "draft"; external_payment_id: str = ""; comment: str = ""
class BankExchangeBatchData(BaseModel): provider_name: str = "bank_api"; direction: str = "outbound"; batch_type: str = "payment_exchange"; bank_account_id: int = 0; payment_order_ids: list[int] = []; result_items: list[dict] = []; comment: str = ""
class AccountingEDOOperatorData(BaseModel): operator_name: str = ""; provider_name: str = "1С-ЭДО"; contour_type: str = "reporting"; api_endpoint: str = ""; account_login: str = ""; credential_ref: str = ""; legal_entity_id: int = 0; business_unit_id: int = 0; status: str = "active"; capabilities: list[str] = []; retry_policy: dict = {}; idempotency_namespace: str = ""
class AccountingExternalReportData(BaseModel): operator_id: int = 0; contour_type: str = "reporting"; report_type: str = ""; period_key: str = ""; legal_entity_id: int = 0; business_unit_id: int = 0; entity_type: str = ""; entity_id: int = 0; payload: dict = {}; idempotency_key: str = ""; comment: str = ""; force_resend: int = 0
class AccountingExternalStatusSyncData(BaseModel): submission_status: str = ""; external_submission_id: str = ""; protocol_number: str = ""; receipt_number: str = ""; message: str = ""; response_payload: dict = {}
class ERPFlowStartData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; title: str = ""; request_type: str = "purchase"; scenario: list = []; due_date: str = ""; amount: float = 0; currency: str = "RUB"; target_role: str = ""; assignee_name: str = ""; approver_name: str = ""; approver_role: str = "Директор"; priority: str = "normal"; item_article: str = ""; item_name: str = ""; qty: float = 0; unit: str = "шт"; unit_price: float = 0; supplier: str = ""; order_name: str = ""; responsible: str = ""; recipient_email: str = ""; comment: str = ""; autoroute: int = 1
class ERPFlowAdvanceData(BaseModel): target_stage: str = ""; status: str = ""; note: str = ""; due_date: str = ""; amount: float = 0; currency: str = "RUB"; approver_name: str = ""; approver_role: str = "Директор"; item_article: str = ""; item_name: str = ""; qty: float = 0; unit: str = "шт"; unit_price: float = 0; supplier: str = ""; order_name: str = ""; responsible: str = ""; recipient_email: str = ""; payment_kind: str = "incoming"; comment: str = ""
class ClientMergeData(BaseModel): master_id: int; duplicate_ids: list[int] = []
class NomenclatureMergeData(BaseModel): master_article: str; duplicate_articles: list[str] = []
class EPLDriverData(BaseModel): full_name: str = ""; personnel_number: str = ""; license_number: str = ""; license_category: str = ""; phone: str = ""; medical_valid_to: str = ""; signature_profile: str = "УНЭП"; status: str = "active"; comment: str = ""
class EPLVehicleData(BaseModel): registration_no: str = ""; garage_number: str = ""; brand: str = ""; model: str = ""; trailer_registration: str = ""; odometer: float = 0; carrying_capacity: float = 0; diagnostic_valid_to: str = ""; insurance_valid_to: str = ""; status: str = "active"; comment: str = ""
class EPLWaybillData(BaseModel): project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; number: str = ""; issue_date: str = ""; shift_date: str = ""; waybill_type: str = "truck"; driver_id: int = 0; vehicle_id: int = 0; route_text: str = ""; cargo: str = ""; departure_point: str = ""; destination_point: str = ""; dispatcher_name: str = ""; medical_name: str = ""; mechanic_name: str = ""; planned_departure: str = ""; actual_departure: str = ""; actual_return: str = ""; odometer_out: float = 0; odometer_in: float = 0; fuel_issued: float = 0; fuel_returned: float = 0; status: str = "draft"; integration_status: str = "draft"; operator_name: str = "1С-ЭДО"; external_document_id: str = ""; last_sync_error: str = ""; notes: str = ""; expected_version: int = 0
class EPLWaybillActionData(BaseModel): stage: str = ""; signer_role: str = ""; signer_name: str = ""; status_value: str = "done"; signed_at: str = ""; comment: str = ""; signature_kind: str = "УНЭП"; integration_status: str = ""; external_document_id: str = ""; last_sync_error: str = ""; expected_version: int = 0
class EPLWaybillReopenData(BaseModel): comment: str = ""; expected_version: int = 0
class EmailAccountData(BaseModel): label: str; address: str; login: str; password: str; imap_host: str = "imap.yandex.ru"; imap_port: int = 993; smtp_host: str = "smtp.yandex.ru"; smtp_port: int = 465; smtp_login: str = ""; smtp_password: str = ""; inbox_folder: str = "INBOX"; archive_folder: str = "Archive"; is_default: int = 0; is_active: int = 1
class EmailMessageStateData(BaseModel): read: int = 1

class SignatureData(BaseModel): email: str; signature: str
class RemoveUserData(BaseModel): email: str
class VacationData(BaseModel): email: str; abs_start: str; abs_end: str; abs_type: str; abs_reason: str; deputy: str
class HRLeaveRequestData(BaseModel): user_email: str = ""; leave_type: str = "vacation"; date_from: str = ""; date_to: str = ""; deputy_name: str = ""; status: str = "pending"; comment: str = ""
class HRTimesheetEntryData(BaseModel): user_email: str = ""; entry_date: str = ""; project_id: int = 0; hours: float = 0; work_mode: str = "office"; status: str = "submitted"; comment: str = ""
class HREquipmentRequestData(BaseModel): user_email: str = ""; category: str = "workplace"; item_name: str = ""; qty: int = 1; needed_by: str = ""; justification: str = ""; status: str = "pending"; comment: str = ""
class HRSubstitutionRequestData(BaseModel): user_email: str = ""; substitute_name: str = ""; date_from: str = ""; date_to: str = ""; reason: str = ""; status: str = "pending"; comment: str = ""
class HRBusinessTripRequestData(BaseModel): user_email: str = ""; destination: str = ""; date_from: str = ""; date_to: str = ""; purpose: str = ""; transport_mode: str = ""; estimated_cost: float = 0; status: str = "pending"; comment: str = ""
class UserScopeData(BaseModel): email: str; allowed_legal_entities: list[int] = []; allowed_business_units: list[int] = []; two_factor_enabled: int = 0
class SessionRevokeData(BaseModel): session_id: str; user_email: str = ""
class TwoFactorCodeData(BaseModel): otp_code: str = ""
class FieldAccessRuleData(BaseModel): role: str = ""; module: str = ""; entity_type: str = ""; field_name: str = ""; can_view: int = 1; can_edit: int = 1; allowed_statuses: list[str] = []; is_active: int = 1
class BankAccountData(BaseModel): name: str = ""; bank_name: str = ""; account_number: str = ""; bik: str = ""; currency: str = "RUB"; legal_entity_id: int = 0; is_active: int = 1
class BankStatementLineData(BaseModel): bank_account_id: int = 0; line_date: str = ""; amount: float = 0; direction: str = "incoming"; counterparty: str = ""; purpose: str = ""; client_id: int = 0; payment_id: int = 0; external_line_id: str = ""; comment: str = ""
class BankStatementImportData(BaseModel): bank_account_id: int = 0; lines: list[BankStatementLineData] = []
class BankStatementReconcileData(BaseModel): payment_id: int = 0
class TelephonyAccountData(BaseModel): provider_name: str = ""; line_name: str = ""; external_line_id: str = ""; is_active: int = 1
class TelephonyCallData(BaseModel): account_id: int = 0; client_id: int = 0; project_id: int = 0; contact_name: str = ""; phone_number: str = ""; direction: str = "inbound"; status: str = "answered"; duration_sec: int = 0; call_at: str = ""; summary: str = ""; recording_url: str = ""
class SavedReportData(BaseModel): report_type: str = "finance_analytics"; title: str = ""; filters: dict = {}; layout: dict = {}; scope: str = "private"
class WorkbenchQuickItemData(BaseModel): entity_type: str = ""; entity_id: str = ""; title: str = ""; meta: str = ""; view_name: str = ""; payload: dict = {}
class WorkbenchSavedFilterData(BaseModel): filter_scope: str = "dashboard"; title: str = ""; filter_payload: dict = {}
class WorkbenchFormDraftData(BaseModel): draft_key: str = ""; entity_type: str = ""; entity_id: str = ""; title: str = ""; payload: dict = {}; source_view: str = ""
class WorkbenchBulkActionData(BaseModel): entity_type: str = ""; action: str = ""; ids: list[int] = []; status: str = ""; assignee: str = ""; comment: str = ""; connector_id: int = 0
class EntityLockData(BaseModel): entity_type: str = ""; entity_id: str = ""; force: int = 0
class SystemRecoveryActionData(BaseModel): action_name: str = ""; older_than_minutes: int = 15; comment: str = ""; force_failed: int = 0; stale_only: int = 1
class DocumentTemplateData(BaseModel): title: str = ""; doc_type: str = "incoming"; template_kind: str = "catalog"; version_label: str = "v1"; body_text: str = ""; variables: list = []; status: str = "draft"; comment: str = ""
class DocumentOCRJobData(BaseModel): document_id: int = 0; file_revision_id: int = 0; source_file: str = ""; input_text: str = ""; language: str = "rus"; template_id: int = 0; auto_apply: int = 0
class DocumentTemplateFlowData(BaseModel): flow_code: str = ""; flow_name: str = ""; direction: str = "incoming"; doc_type: str = "incoming"; trigger_rules: dict = {}; template_ids: list[int] = []; required_fields: list[str] = []; status: str = "active"
class DocumentTemplateFlowApplyData(BaseModel): document_id: int = 0; ocr_job_id: int = 0; comment: str = ""
class DocumentVersionRecordData(BaseModel): document_id: int = 0; version_label: str = ""; version_status: str = "draft"; payload: dict = {}; file_url: str = ""; comment: str = ""
class DocumentLinkedTaskData(BaseModel): document_id: int = 0; task_id: int = 0; title: str = ""; assignee_name: str = ""; deadline: str = ""; priority: str = "normal"; status: str = "active"; comment: str = ""
class DocumentWorkflowStartData(BaseModel): approval_title: str = ""; route_rules: list[dict] = []; route_context: dict = {}; comment: str = ""
class EDOCertificateData(BaseModel): owner_name: str = ""; owner_email: str = ""; signer_role: str = ""; provider_name: str = "1С-ЭДО"; thumbprint: str = ""; serial_number: str = ""; valid_from: str = ""; valid_to: str = ""; status: str = "active"; comment: str = ""
class LegalArchiveEntryData(BaseModel): document_id: int = 0; archive_code: str = ""; storage_path: str = ""; retention_until: str = ""; archive_status: str = "archived"; certificate_id: int = 0; comment: str = ""; policy_id: int = 0; access_roles: list[str] = []; transfer_basis: str = ""; destruction_basis: str = ""; review_due_at: str = ""
class PrintFormRecordData(BaseModel): document_id: int = 0; template_id: int = 0; format_type: str = "pdf"; form_name: str = ""; file_url: str = ""; status: str = "generated"; comment: str = ""
class DocumentRegistrationJournalData(BaseModel): journal_code: str = ""; journal_name: str = ""; doc_type: str = ""; prefix: str = ""; numbering_pattern: str = "{prefix}-{year}-{number}"; is_active: int = 1
class DocumentClassifierData(BaseModel): classifier_code: str = ""; name: str = ""; doc_type: str = ""; category: str = ""; required_fields: list[str] = []; default_lifecycle: str = "draft"; retention_years: int = 5; is_active: int = 1; allowed_roles: list[str] = []; retention_policy_id: int = 0
class DocumentCaseFileData(BaseModel): case_index: str = ""; title: str = ""; department: str = ""; retention_years: int = 5; opened_at: str = ""; closed_at: str = ""; status: str = "open"; responsible_name: str = ""; case_category: str = ""; allowed_roles: list[str] = []; retention_policy_id: int = 0; transfer_basis_default: str = ""; destruction_basis_default: str = ""
class DocumentLegalCardData(BaseModel): journal_id: int = 0; classifier_id: int = 0; case_file_id: int = 0; legal_significance: str = "standard"; confidentiality_level: str = "internal"; retention_until: str = ""; document_kind_code: str = ""; auto_register: int = 1; comment: str = ""
class DocumentLifecycleActionData(BaseModel): action_name: str = ""; target_state: str = ""; comment: str = ""
class DocumentSignatureActionData(BaseModel): certificate_id: int = 0; certificate_thumbprint: str = ""; signature_kind: str = "КЭП"; signature_provider: str = "1С-ЭДО"; signer_name: str = ""; signer_role: str = ""; signed_at: str = ""; comment: str = ""; force_archive: int = 0
class DocumentSignatureVerifyData(BaseModel): comment: str = ""; force: int = 0
class CryptoSignatureSessionData(BaseModel): file_revision_id: int = 0; certificate_id: int = 0; certificate_thumbprint: str = ""; signature_kind: str = "КЭП"; signature_provider: str = "КриптоПро"; signature_format: str = "CAdES detached"; signer_name: str = ""; signer_role: str = ""; comment: str = ""
class CryptoSignatureProtocolData(BaseModel): protocol_status: str = "attached"; protocol_number: str = ""; validation_result: str = ""; validation_message: str = ""; provider: str = "КриптоПро"; checks: dict = {}; raw_protocol: dict = {}; comment: str = ""
class DocumentPackageData(BaseModel): package_number: str = ""; title: str = ""; package_kind: str = "contract_set"; document_ids: list[int] = []; items: list[dict] = []; project_id: int = 0; client_id: int = 0; contract_id: int = 0; object_id: int = 0; comment: str = ""
class DocumentPackageApprovalData(BaseModel): route_rules: list[dict] = []; comment: str = ""; default_sla_hours: int = 24
class DocumentPackageSignData(BaseModel): signer_name: str = ""; signer_role: str = ""; comment: str = ""; strict: int = 0
class DocumentLegalArchiveActionData(BaseModel): archive_code: str = ""; storage_path: str = ""; retention_until: str = ""; archive_status: str = "archived"; comment: str = ""; policy_id: int = 0; access_roles: list[str] = []; transfer_basis: str = ""; destruction_basis: str = ""; review_due_at: str = ""
class DocumentRetentionPolicyData(BaseModel): policy_code: str = ""; policy_name: str = ""; scope_type: str = "doc_type"; scope_value: str = ""; retention_years: int = 5; review_before_days: int = 90; auto_archive: int = 0; transfer_basis_default: str = ""; destruction_basis_default: str = ""; access_roles: list[str] = []; confidentiality_levels: list[str] = []; is_active: int = 1; comment: str = ""
class DocumentRetentionDispositionData(BaseModel): action_name: str = "review"; archive_id: int = 0; archive_status: str = ""; basis_text: str = ""; storage_path: str = ""; retention_until: str = ""; review_due_at: str = ""; comment: str = ""
class IntegrationFieldMappingData(BaseModel): system_name: str = "1C"; entity_type: str = ""; local_field: str = ""; external_field: str = ""; direction: str = "bidirectional"; transform_rule: str = ""; is_required: int = 0; is_active: int = 1
class IntegrationInboundUpdateRecordData(BaseModel): system_name: str = "1C"; entity_type: str = ""; entity_id: int = 0; external_id: str = ""; payload: dict = {}; apply_mode: str = "apply"; comment: str = ""
class IntegrationConnectorData(BaseModel): connector_type: str = "1c"; provider_name: str = ""; status: str = "active"; settings: dict = {}; scope: dict = {}; last_error: str = ""
class OneCConnectorData(BaseModel): id: int = 0; provider_name: str = "1C"; status: str = "active"; transport: str = "demo"; mode: str = ""; base_url: str = ""; endpoint_template: str = ""; timeout_seconds: int = 20; settings: dict = {}; scope: dict = {}
class OneCConnectorCredentialData(BaseModel): credential_kind: str = "basic"; username: str = ""; password: str = ""; secret_value: str = ""; secret_ref: str = ""
class OneCBatchExportData(BaseModel): entity_type: str = ""; entity_ids: list = []; connector_id: int = 0; idempotency_key: str = ""
class SecurityActionPolicyData(BaseModel): role_name: str = ""; module_name: str = ""; entity_type: str = ""; action_name: str = ""; status_name: str = ""; allow_execute: int = 1; require_2fa: int = 0; require_reason: int = 0; is_active: int = 1
class SecurityDangerRuleData(BaseModel): module_name: str = ""; entity_type: str = ""; action_name: str = ""; risk_level: str = "medium"; require_2fa: int = 0; require_reason: int = 1; blocked_roles: list = []; is_active: int = 1; comment: str = ""
class SecuritySessionControlData(BaseModel): user_email: str = ""; session_id: str = ""; action_name: str = "revoke_all"; older_than_minutes: int = 0; reason: str = ""
class SecurityGuardCheckData(BaseModel): module_name: str = ""; entity_type: str = ""; action_name: str = ""; status_name: str = ""; reason: str = ""
class MeetingData(BaseModel): title: str; m_date: str; m_time: str; participants: list = []; agenda: list = []
class MeetingUpdate(BaseModel): title: str; m_date: str; m_time: str; participants: list = []; agenda: list = []; decisions: dict = {}; status: str
class GlobalChatData(BaseModel): name: str; creator: str; participants: list = []
class GlobalMessageData(BaseModel): user: str; role: str; text: str
class TaskChatMessageData(BaseModel): text: str
class DocData(BaseModel): type: str; number: str; d_date: str; correspondent: str = ""; sender_name: str = ""; recipient_name: str = ""; source_number: str = ""; source_date: str = ""; delivery_method: str = ""; signer_name: str = ""; executor_name: str = ""; subject: str; status: str; project_id: int = 0; contract_id: int = 0; object_id: int = 0; parent_id: int = 0; priority: str = "normal"; resolution: str = ""; resolution_author: str = ""; resolution_deadline: str = ""; resolution_assignee: str = ""; resolution_task_id: int = 0
class DocUpdate(BaseModel): type: str; number: str; d_date: str; correspondent: str = ""; sender_name: str = ""; recipient_name: str = ""; source_number: str = ""; source_date: str = ""; delivery_method: str = ""; signer_name: str = ""; executor_name: str = ""; subject: str; status: str; project_id: int = 0; contract_id: int = 0; object_id: int = 0; parent_id: int = 0; priority: str = "normal"; resolution: str = ""; resolution_author: str = ""; resolution_deadline: str = ""; resolution_assignee: str = ""; resolution_task_id: int = 0
class TaskData(BaseModel): title: str; description: str; author: str; executor: str; deadline: str; recurrence: str = "none"; priority: str = "normal"; project_id: int = 0
class TaskUpdate(BaseModel): status: str | None = None; executor: str | None = None; history: list | None = None; priority: str | None = None; title: str | None = None; description: str | None = None; deadline: str | None = None; project_id: int | None = None
class CompanyFeedPostData(BaseModel): post_type: str = "announcement"; title: str = ""; content: str = ""; poll_options: list[dict] = []; target_roles: list[str] = []; is_pinned: int = 0
class CompanyFeedCommentData(BaseModel): text: str = ""
class CompanyFeedReactionData(BaseModel): reaction_key: str = "like"
class CompanyFeedVoteData(BaseModel): option_key: str = ""
class CompanyFeedPinData(BaseModel): is_pinned: int = 0
class KnowledgeData(BaseModel): title: str; content: str; author: str; required_roles: list = []
class KnowledgeReadData(BaseModel): user: str
class ApprovalData(BaseModel): title: str; item_link: str; route: list = []; author: str; entity_type: str = ""; entity_id: str = ""; route_rules: list[dict] = []; route_context: dict = {}; required_comment_on_reject: int = 1; required_comment_on_return: int = 1; default_sla_hours: int = 24; escalation_role: str = "Директор"
class ApprovalUpdate(BaseModel): current_step: int = 0; status: str = "pending"; history: list = []; route: list = []; current_stage_key: str = ""; approval_state: dict = {}
class ApprovalActionData(BaseModel): action_name: str = ""; comment: str = ""; target_user: str = ""; target_stage_key: str = ""; reason: str = ""; force: int = 0
class ApprovalRouteTemplateData(BaseModel): route_code: str = ""; route_name: str = ""; entity_type: str = ""; conditions: dict = {}; stages: list[dict] = []; is_active: int = 1; comment: str = ""
class WorkflowDefinitionData(BaseModel): workflow_code: str = ""; workflow_name: str = ""; entity_type: str = ""; trigger_event: str = "manual"; version: int = 1; status: str = "active"; conditions: dict = {}; settings: dict = {}; nodes: list[dict] = []; edges: list[dict] = []; is_active: int = 1; comment: str = ""
class WorkflowStartData(BaseModel): entity_type: str = ""; entity_id: str = ""; title: str = ""; context: dict = {}; comment: str = ""
class WorkflowTokenActionData(BaseModel): action_name: str = ""; comment: str = ""; target_user: str = ""; target_node_key: str = ""; force: int = 0
